
services:
  fastapi_app:
    build: .
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - redis_cache
    env_file:
      - .env
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes:
      - .:/app
    networks:
      - app_network

  redis_cache:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app_network

  celery_worker:
    build: .
    container_name: celery_worker
    restart: always
    depends_on:
      - redis_cache
    env_file:
      - .env
    command:  ["celery", "-A", "app.workers.celery_worker", "worker", "--loglevel=info"]

    volumes:
      - .:/app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
