version: '3.8'

services:
  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:root@db:5432/moderation_db
      - REDIS_URL=redis://redis:6379/0

  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: moderation_db
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"

  worker:
    build: .
    container_name: celery_worker
    command: celery -A app.workers.celery_worker worker --loglevel=info
    depends_on:
      - redis
      - db
